CREATE TABLE CATEGORIA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE PRODUTO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    PRECO DECIMAL(10,2),
    CATEGORIA_ID BIGINT,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

CREATE TABLE CLIENTE (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(255)
);

CREATE TABLE PEDIDO (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	DATA DATETIME,
	CLIENTE_ID BIGINT,
	FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);	

CREATE TABLE ITEM_PEDIDO (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	PEDIDO_ID BIGINT,
	FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID),
	PRODUTO_ID BIGINT,
	FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID),
	PRECO_UNITARIO DECIMAL(10.2),
	QUANTIDADE INTEGER
)
